export const items = [
    // Phones
    {
      id: 1,
      category: "phones",
      title: "Apple iPhone 14 Pro",
      imgSrc: "https://m.media-amazon.com/images/I/61XO4bORHUL._SL1500_.jpg",
      amazonLink: "https://example.com/iphone14pro",
      flipkartLink: "https://www.flipkart.com/apple-iphone-14-pro-deep-purple-256-gb/p/itm75f73f63239fa",
      description: "Apple iPhone 14 Pro (256 GB) - Deep Purple",
      price: "129999",
    },
    {
      id: 2,
      category: "phones",
      title: "Samsung Galaxy S23 Ultra",
      imgSrc: "https://m.media-amazon.com/images/I/61VfL-aiToL._SL1500_.jpg",
      amazonLink: "https://example.com/galaxys23ultra",
      flipkartLink: "https://www.flipkart.com/samsung-galaxy-s23-ultra-5g-phantom-black-256-gb/p/itm77dc35f6a5e4b",
      description: "Samsung Galaxy S23 Ultra 5G (256GB) - Phantom Black",
      price: "124999",
    },
    {
      id: 3,
      category: "phones",
      title: "Google Pixel 7 Pro",
      imgSrc: "https://m.media-amazon.com/images/I/71AvQd3VzqL._SL1500_.jpg",
      amazonLink: "https://example.com/pixel7pro",
      flipkartLink: "https://www.flipkart.com/google-pixel-7-pro-hazel-128-gb/p/itmdb77f9e6d1403",
      description: "Google Pixel 7 Pro (128 GB) - Hazel",
      price: "84999",
    },
  
    // Tablets
    {
      id: 4,
      category: "tablets",
      title: "Apple iPad Air",
      imgSrc: "https://m.media-amazon.com/images/I/61XZQXFQeVL._SL1500_.jpg",
      amazonLink: "https://example.com/ipadair",
      flipkartLink: "https://www.flipkart.com/apple-ipad-air-5th-gen-64-gb-rom-10-9-inch-wi-fi-only-space-grey/p/itm9aa30fc4df5d8",
      description: "Apple iPad Air (5th Generation) | 10.9-inch | M1 chip",
      price: "59900",
    },
    {
      id: 5,
      category: "tablets",
      title: "Samsung Galaxy Tab S8",
      imgSrc: "https://m.media-amazon.com/images/I/81d74GHCPEL._SL1500_.jpg",
      amazonLink: "https://example.com/galaxytabs8",
      flipkartLink: "https://www.flipkart.com/samsung-galaxy-tab-s8-wi-fi-android-tablet-8-gb-ram-128-rom-11-inches/p/itm53b9947805b64",
      description: "Samsung Galaxy Tab S8 | 11-inch | Wi-Fi",
      price: "58999",
    },
    {
      id: 6,
      category: "tablets",
      title: "Microsoft Surface Pro 9",
      imgSrc: "https://m.media-amazon.com/images/I/61Z7OHZXrnL._SL1500_.jpg",
      amazonLink: "https://example.com/surfacepro9",
      flipkartLink: "https://www.flipkart.com/microsoft-surface-pro-9-core-i5-12th-gen-8-gb-256-gb-ssd-windows-11-home-13-tablet/p/itm4e7a5fc0c0a95",
      description: "Microsoft Surface Pro 9 | 13-inch | Intel Core i5",
      price: "105999",
    },
  
    // Laptops
    {
      id: 7,
      category: "laptops",
      title: "Apple MacBook Pro",
      imgSrc: "https://m.media-amazon.com/images/I/61L5QgPvgqL._SL1500_.jpg",
      amazonLink: "https://example.com/macbookpro",
      flipkartLink: "https://www.flipkart.com/apple-2023-macbook-pro-m2-pro-chip-16-gb-512-gb-ssd-macos-ventura-mphf3hn-a/p/itm4d7f350efe1cf",
      description: "Apple MacBook Pro | 14-inch | M2 Pro chip",
      price: "199900",
    },
    {
      id: 8,
      category: "laptops",
      title: "Dell XPS 15",
      imgSrc: "https://m.media-amazon.com/images/I/71jG+e7roXL._SL1500_.jpg",
      amazonLink: "https://example.com/dellxps15",
      flipkartLink: "https://www.flipkart.com/dell-xps-15-core-i7-12th-gen-32-gb-1-tb-ssd-windows-11-home-4-gb-graphics-nvidia-geforce-rtx-3050-ti-9520-thin-light-laptop/p/itm4e7a5a6a1e016",
      description: "Dell XPS 15 | 15.6-inch | Intel Core i7 | 16GB RAM",
      price: "179999",
    },
    {
      id: 9,
      category: "laptops",
      title: "Lenovo ThinkPad X1 Carbon",
      imgSrc: "https://m.media-amazon.com/images/I/71krmFgx5pL._SL1500_.jpg",
      amazonLink: "https://example.com/thinkpadx1",
      flipkartLink: "https://www.flipkart.com/lenovo-thinkpad-x1-carbon-core-i5-11th-gen-16-gb-512-gb-ssd-windows-10-home-14-thin-light-laptop/p/itm3e4e7c1b99128",
      description: "Lenovo ThinkPad X1 Carbon | 14-inch | Intel Core i5",
      price: "149999",
    },
  
    // Watches
    {
      id: 10,
      category: "watches",
      title: "Apple Watch Series 8",
      imgSrc: "https://m.media-amazon.com/images/I/71XMTLtZd5L._SL1500_.jpg",
      amazonLink: "https://example.com/applewatch8",
      flipkartLink: "https://www.flipkart.com/apple-watch-series-8-gps-cellular-45-mm-midnight-aluminium-case-sport-band/p/itm4d1e8e2a4e7d1",
      description: "Apple Watch Series 8 | GPS + Cellular | 45mm",
      price: "45900",
    },
    {
      id: 11,
      category: "watches",
      title: "Samsung Galaxy Watch 5 Pro",
      imgSrc: "https://m.media-amazon.com/images/I/61Sl+xoVHoL._SL1500_.jpg",
      amazonLink: "https://example.com/galaxywatch5pro",
      flipkartLink: "https://www.flipkart.com/samsung-galaxy-watch5-pro-bluetooth-45mm-super-amoled-display/p/itm3d2b46c7e8fb8",
      description: "Samsung Galaxy Watch 5 Pro | Bluetooth | 45mm",
      price: "44999",
    },
    {
      id: 12,
      category: "watches",
      title: "Garmin Fenix 7",
      imgSrc: "https://m.media-amazon.com/images/I/71RGKLWCmKL._SL1500_.jpg",
      amazonLink: "https://example.com/garminfenix7",
      flipkartLink: "https://www.flipkart.com/garmin-fenix-7-smartwatch/p/itm0e9b4d3e8e03d",
      description: "Garmin Fenix 7 | Multisport GPS Smartwatch",
      price: "69999",
    },
  
    // Earbuds
    {
      id: 13,
      category: "earbuds",
      title: "Apple AirPods Pro",
      imgSrc: "https://m.media-amazon.com/images/I/61SUj2aKoEL._SL1500_.jpg",
      amazonLink: "https://example.com/airpodspro",
      flipkartLink: "https://www.flipkart.com/apple-airpods-pro-2nd-generation-active-noise-cancellation-enabled-bluetooth-headset/p/itm5d6a8e0e3d2b2",
      description: "Apple AirPods Pro (2nd Generation)",
      price: "26900",
    },
    {
      id: 14,
      category: "earbuds",
      title: "Sony WF-1000XM4",
      imgSrc: "https://m.media-amazon.com/images/I/61G9yF+ZbEL._SL1500_.jpg",
      amazonLink: "https://example.com/sonywf1000xm4",
      flipkartLink: "https://www.flipkart.com/sony-wf-1000xm4-industry-leading-noise-cancellation-bluetooth-headset/p/itm57e7bd2ad9561",
      description: "Sony WF-1000XM4 | Noise Cancelling Truly Wireless Earbuds",
      price: "19990",
    },
    {
      id: 15,
      category: "earbuds",
      title: "Jabra Elite 7 Pro",
      imgSrc: "https://m.media-amazon.com/images/I/61C2xGf1WDL._SL1500_.jpg",
      amazonLink: "https://example.com/jabraelite7pro",
      flipkartLink: "https://www.flipkart.com/jabra-elite-7-pro-bluetooth-headset/p/itm9a4a2c2c2b3d7",
      description: "Jabra Elite 7 Pro | True Wireless Earbuds",
      price: "16999",
    },
  
    // Headphones
    {
      id: 16,
      category: "headphones",
      title: "Sony WH-1000XM5",
      imgSrc: "https://m.media-amazon.com/images/I/61+btxzpfDL._SL1500_.jpg",
      amazonLink: "https://example.com/sonywh1000xm5",
      flipkartLink: "https://www.flipkart.com/sony-wh-1000xm5-bluetooth-headset/p/itm56a9b5a8c4460",
      description: "Sony WH-1000XM5 | Wireless Noise Cancelling Headphones",
      price: "34990",
    },
    {
      id: 17,
      category: "headphones",
      title: "Bose QuietComfort 45",
      imgSrc: "https://m.media-amazon.com/images/I/51JbsHSktkL._SL1500_.jpg",
      amazonLink: "https://example.com/boseqc45",
      flipkartLink: "https://www.flipkart.com/bose-quietcomfort-45-bluetooth-headset/p/itm9e8e2a9c2e7f7",
      description: "Bose QuietComfort 45 | Wireless Noise Cancelling Headphones",
      price: "29900",
    },
    {
      id: 18,
      category: "headphones",
      title: "Sennheiser Momentum 4",
      imgSrc: "https://m.media-amazon.com/images/I/71YKGpLOj5L._SL1500_.jpg",
      amazonLink: "https://example.com/sennheisermomentum4",
      flipkartLink: "https://www.flipkart.com/sennheiser-momentum-4-wireless-bluetooth-headset/p/itm5e7a5a6a1e016",
      description: "Sennheiser Momentum 4 | Wireless Headphones",
      price: "34990",
    },
  
    // Bluetooth Speakers
    {
      id: 19,
      category: "bluetooth",
      title: "JBL Flip 6",
      imgSrc: "https://m.media-amazon.com/images/I/61+SNIG1ZML._SL1500_.jpg",
      amazonLink: "https://example.com/jblflip6",
      flipkartLink: "https://www.flipkart.com/jbl-flip-6-20-w-bluetooth-speaker/p/itm4e7a5a6a1e016",
      description: "JBL Flip 6 | Portable Waterproof Bluetooth Speaker",
      price: "9999",
    },
    {
      id: 20,
      category: "bluetooth",
      title: "Sonos Roam",
      imgSrc: "https://m.media-amazon.com/images/I/61zPXxXYJPL._SL1500_.jpg",
      amazonLink: "https://example.com/sonosroam",
      flipkartLink: "https://www.flipkart.com/sonos-roam-10-w-bluetooth-speaker/p/itm4e7a5a6a1e016",
      description: "Sonos Roam | Smart Portable Wi-Fi and Bluetooth Speaker",
      price: "19900",
    },
    {
      id: 21,
      category: "bluetooth",
      title: "Bose SoundLink Revolve+ II",
      imgSrc: "https://m.media-amazon.com/images/I/71JB6hM6Z6L._SL1500_.jpg",
      amazonLink: "https://example.com/bosesoundlinkrevolveplusii",
      flipkartLink: "https://www.flipkart.com/bose-soundlink-revolve-series-ii-bluetooth-speaker/p/itm4e7a5a6a1e016",
      description: "Bose SoundLink Revolve+ II | Portable Bluetooth Speaker",
      price: "29900",
    },
  ];